### ISSUE TITLE
Initial Development Roadmap

### ISSUE THREAD

**Issue by rickymagner** [broadinstitute/quickboard#1]
## Development 
Here is a list of development goals to achieve in the near future. I'd like to have many if not all before releasing v1.0.0. Priority level is listed at the start of the goal.

### Features
- [ ] (High) Allow for serialization of boards / saving configurations for easier portability
- [x] (Med) Allow `DynamicPanels` to listen to clicks on others and update content accordingly (Dash interactive visualization)
- [ ] (Med) Add more plugins, example templates, etc. 
- [ ] (Med) Better implement dynamic text boxes and have more variety
- [x] (Low) Allow better access to styling individual components through comprehensive style handling; make defaults more robust and input based
- [x] (Low) Add toggle all/none buttons for Checklist plugins

### Usage
- [X] (High) Eliminate the need for inputting `parent_id` into plugins (Done as of v0.2.0)
- [x] (Med) Allow more variety in how users define headers (strings vs HTML objects); handle uniformly across objects; also get plugin headers to appear correctly in `dbc.Toast`
- [X] (Low) Test using defaults/auto-gen `html_id` strings (Done as of v0.2.0)
- [X] (Low) Test removing the `fig_postprocess` method from `PlotPanel`'s in favor of using custom `plotter`'s (Done as of v0.2.0)

### Performance
- [ ] (High) Consider adding [memoization](https://dash.plotly.com/performance)
- [ ] (High) Reorganize imports to make them faster (currently pretty slow to import packages)
- [X] (High) Try to use MATCH pattern-matching callback for easier-to-read plugin code; refactor html_id handling (Done as of v0.2.0)
- [ ] (Med) Use override decorator (and others?) to be able to skip certain function calls that are unnecessary in callback loop
- [ ] (Med) Add loading animations for boards with large datasets
- [ ] (Low) Add type hinting and use mypy

### Docs
- [ ] (Med) Add more examples of advanced usage, including inheritance from base components + full callback loop
- [x] (Med) Make gallery of components and plugins
- [ ] (Med) Transfer docstrings into a living document
- [ ] (Low) Add a complete `.py` and `.ipynb` or two so users can get started with a pre-made template right away
- [ ] (Low) Add suggestions / best practices / FAQ
- [ ] (Low) Add a tutorial board

### Project Organization
- [x] (High) Add package to PyPI and add Install Guide (Done as of v0.1.1)
- [ ] (Med) Add a docker to quickly get started using  the package
- [x] (Low) Add testing folder with test scripts
